[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "french-typo"
version = "1.0.0"
description = "Moteur agnostique de correction typographique franÃ§aise"
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }

[tool.setuptools.packages.find]
where = ["."]
include = ["french_typo*"]
